use crate::value_parser;
use clap::arg;
use clap::Command;
use clap::{Arg, ArgMatches};

pub fn parse_args() -> ArgMatches {
    let version = env!("CARGO_PKG_VERSION");
    Command::new("rush")
            .version(version)
            .author("Troels F. Rønnow <troels@wonop.com>")
            .about("Rush is designed as an all-around support unit for developers, transforming the development workflow with its versatile capabilities. It offers a suite of tools for building, deploying, and managing applications, adapting to the diverse needs of projects with ease.")
            .arg(arg!(target_arch : --arch <TARGET_ARCH> "Target architecture"))
            .arg(arg!(target_os : --os <TARGET_OS> "Target OS"))
            .arg(arg!(environment : --env <ENVIRONMENT> "Environment"))
            .arg(arg!(docker_registry : --registry <DOCKER_REGISTRY> "Docker Registry"))
            .arg(arg!(log_level : -l --loglevel <LOG_LEVEL> "Log level (trace, debug, info, warn, error)").default_value("info"))
            .arg(arg!(start_port: --port <START_PORT> "Starting port for services").value_parser(value_parser!(u16)).default_value("8129"))
            .arg(Arg::new("product_name").required(true))
            .subcommand(Command::new("describe")
                .about("Describes the current configuration")
                .subcommand(Command::new("toolchain")
                    .about("Describes the current toolchain")
                )
                .subcommand(Command::new("images")
                    .about("Describes the current images")
                )
                .subcommand(Command::new("services")
                    .about("Describes the current services")
                )
                .subcommand(Command::new("build-script")
                    .about("Describes the current build script")
                    .arg(Arg::new("component_name").required(true))
                )
                .subcommand(Command::new("build-context")
                    .about("Describes the current build context")
                    .arg(Arg::new("component_name").required(true))
                )
                .subcommand(Command::new("artefacts")
                    .about("Describes the current artefacts")
                    .arg(Arg::new("component_name").required(true))
                )
                .subcommand(Command::new("k8s")
                    .about("Describes the current k8s")
                )
            )
            .subcommand(Command::new("dev")
                .arg(arg!(redirect : --redirect <COMPONENTS> ... "Disables component and redirects the ingress. Format: component@host:port").num_args(1..))
                .arg(arg!(silence : --silence <COMPONENTS> ... "Silence output for specific components").num_args(1..))
            )
            .subcommand(Command::new("build"))
            .subcommand(Command::new("push"))
            .subcommand(Command::new("minikube")
                .about("Runs tasks on minikube")
                .subcommand(Command::new("dev"))
                .subcommand(Command::new("start"))
                .subcommand(Command::new("stop"))
                .subcommand(Command::new("delete"))
            )
            .subcommand(Command::new("rollout")
                .about("Rolls out the product into staging or production")
            )
            .subcommand(Command::new("deploy"))
            .subcommand(Command::new("install"))
            .subcommand(Command::new("uninstall"))
            .subcommand(Command::new("apply"))
            .subcommand(Command::new("unapply"))
            .subcommand(Command::new("validate")
                .about("Validates Kubernetes manifests")
                .subcommand(Command::new("manifests")
                    .about("Validates Kubernetes manifests with schema validation")
                    .arg(arg!(target_version : --version <K8S_VERSION> "Target Kubernetes version"))
                )
                .subcommand(Command::new("deprecations")
                    .about("Checks for deprecated APIs in Kubernetes manifests")
                    .arg(arg!(target_version : --version <K8S_VERSION> "Target Kubernetes version"))
                )
            )
            .subcommand(Command::new("vault")
                .about("Manages vault operations")
                .subcommand(Command::new("create"))
                .subcommand(Command::new("add")
                    .arg(Arg::new("component_name").required(true))
                    .arg(Arg::new("secrets").required(true))
                )
                .subcommand(Command::new("remove")
                    .arg(Arg::new("component_name").required(true))
                )
                .subcommand(Command::new("migrate")
                    .about("Migrates secrets")
                    .arg(Arg::new("dest").required(true))
                )
            )
            .subcommand(Command::new("secrets")
                .about("Manages secrets")
                .subcommand(Command::new("init")
                    .about("Initializes secrets")
                )
            )
            .get_matches()
}
