//! Base implementation for local services
//!
//! This module provides a base implementation with common functionality
//! that can be shared by all local service implementations.

use std::collections::HashMap;
use std::sync::Arc;

use rush_output::simple::{LogEntry, Sink};
use tokio::sync::Mutex;

use crate::types::LocalServiceType;

/// Base implementation for local services with common functionality
pub struct BaseLocalService {
    /// Service name
    pub name: String,

    /// Service type
    pub service_type: LocalServiceType,

    /// Whether the service is running
    pub is_running: bool,

    /// Output sink for logging
    pub output_sink: Option<Arc<Mutex<Box<dyn Sink>>>>,

    /// Environment variables generated by this service
    pub env_vars: HashMap<String, String>,

    /// Secrets generated by this service
    pub env_secrets: HashMap<String, String>,
}

impl BaseLocalService {
    /// Create a new base service
    pub fn new(name: String, service_type: LocalServiceType) -> Self {
        Self {
            name,
            service_type,
            is_running: false,
            output_sink: None,
            env_vars: HashMap::new(),
            env_secrets: HashMap::new(),
        }
    }

    /// Log a message through the output sink
    pub async fn log(&self, message: String, is_error: bool) {
        if let Some(ref sink) = self.output_sink {
            let entry = if is_error {
                LogEntry::docker(&self.name, message).as_error()
            } else {
                LogEntry::docker(&self.name, message)
            };

            let mut sink = sink.lock().await;
            let _ = sink.write(entry).await;
        }
    }

    /// Log an info message
    pub async fn log_info(&self, message: impl Into<String>) {
        self.log(message.into(), false).await;
    }

    /// Log an error message
    pub async fn log_error(&self, message: impl Into<String>) {
        self.log(message.into(), true).await;
    }
}

/// Macro to implement common LocalService trait methods
#[macro_export]
macro_rules! impl_local_service_common {
    ($type:ty) => {
        fn name(&self) -> &str {
            &self.base.name
        }

        fn service_type(&self) -> LocalServiceType {
            self.base.service_type.clone()
        }

        fn is_running(&self) -> bool {
            self.base.is_running
        }

        fn set_output_sink(&mut self, sink: Arc<Mutex<Box<dyn Sink>>>) {
            self.base.output_sink = Some(sink);
        }

        async fn generated_env_vars(&self) -> Result<HashMap<String, String>> {
            Ok(self.base.env_vars.clone())
        }

        async fn generated_env_secrets(&self) -> Result<HashMap<String, String>> {
            Ok(self.base.env_secrets.clone())
        }
    };
}
