//! Local service trait definition
//!
//! This module defines the trait that all local services must implement.

use async_trait::async_trait;
use rush_core::error::Result;
use rush_output::simple::Sink;
use std::collections::HashMap;
use std::sync::Arc;
use tokio::sync::Mutex;

use crate::types::LocalServiceType;

/// Trait that all local services must implement
#[async_trait]
pub trait LocalService: Send + Sync {
    /// Start the service
    async fn start(&mut self) -> Result<()>;
    
    /// Stop the service
    async fn stop(&mut self) -> Result<()>;
    
    /// Check if the service is healthy
    async fn is_healthy(&self) -> Result<bool>;
    
    /// Run post-startup tasks after the service is healthy
    /// Returns Ok(()) if all tasks completed successfully
    async fn run_post_startup_tasks(&mut self) -> Result<()>;
    
    /// Get environment variables generated by this service
    /// (e.g., DATABASE_URL, REDIS_URL)
    async fn generated_env_vars(&self) -> Result<HashMap<String, String>>;
    
    /// Get secrets generated by this service
    /// (e.g., webhook signing secrets from Stripe)
    async fn generated_env_secrets(&self) -> Result<HashMap<String, String>>;
    
    /// Get the service name
    fn name(&self) -> &str;
    
    /// Get the service type
    fn service_type(&self) -> LocalServiceType;
    
    /// Check if the service is currently running
    fn is_running(&self) -> bool;
    
    /// Set the output sink for logging (optional - default implementation does nothing)
    fn set_output_sink(&mut self, _sink: Arc<Mutex<Box<dyn Sink>>>) {
        // Default implementation - services can override if they support output sinks
    }
}