apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ component }}"
  namespace: "{{ product_uri }}-{{ environment }}"
  labels:
    "app.kubernetes.io/name": "{{ product_uri }}-{{ component }}-{{ environment }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      "app.kubernetes.io/name": "{{ product_uri }}-{{ component }}-{{ environment }}"
  strategy:
    type: RollingUpdate

  template:
    metadata:
      labels:
        "app.kubernetes.io/name": "{{ product_uri }}-{{ component }}-{{ environment }}"
    spec:
      containers:
        - image: "{{ docker_registry }}/{{ image_name }}"
          name: "{{ component }}"

          ports:
            - containerPort: 8000
          env:
            - name: DUMMY
              valueFrom:
                secretKeyRef:
                  name: "{{ component }}"
                  key: dummy
