apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: "{{ component }}-ingress"
  namespace: "{{ product_uri }}-{{ environment }}"
  annotations:
  labels:
    app.kubernetes.io/name: "{{ component }}"
    app.kubernetes.io/instance: "{{ component }}-default"
spec:
  entryPoints:
    - web
  routes:
    - match: Host("{{ domain }}") && PathPrefix("/api")
      kind: Rule
      services:
        - name: "{{ component }}-service"
          port: 80
