apiVersion: v1
kind: Namespace
metadata:
  name: demo-bazel
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-bazel
  namespace: demo-bazel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-bazel
  template:
    metadata:
      labels:
        app: demo-bazel
    spec:
      containers:
      - name: demo-bazel
        image: {{ image_name }}
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: demo-bazel
  namespace: demo-bazel
spec:
  selector:
    app: demo-bazel
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
