apiVersion: v1
kind: Service
metadata:
  name: "{{ component }}-service"
  namespace: "{{ product_uri }}-{{ environment }}"
  labels:
    "app.kubernetes.io/name": "{{ product_uri }}-{{ component }}-{{ environment }}"

spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8000
  selector:
    "app.kubernetes.io/name": "{{ product_uri }}-{{ component }}-{{ environment }}"
